### ISSUE TITLE
Add the branching strategy to the `README`

### ISSUE THREAD

**Issue by John15321** [John15321/rust-pip#28]
![image](https://user-images.githubusercontent.com/56229312/184718893-e65f480f-f3e9-44a7-855c-2a300a75c676.png)

**Comment by John15321** [comment]
commit intellectual theft

**Comment by MiscStuff839** [comment]
Could you elaborate on what needs to be done?

**Comment by MiscStuff839** [comment]
I think the tag part is a bit redundant seeing as when anything happens on master it means it is to be released.

**Comment by John15321** [comment]
> I think the tag part is a bit redundant seeing as when anything happens on master it means it is to be released.

That's does not have to be the case
Also don't worry i will do it myself

**Comment by John15321** [comment]
Sorry I forgot to assign myself
