### ISSUE TITLE
Add a `CHANGELOG` file

### ISSUE THREAD

**Issue by John15321** [John15321/rust-pip#32]
Add a changelog file. What is a changelog file:
* https://www.youtube.com/watch?v=Pi8akLplC9M&ab_channel=NickJanetakis
* https://keepachangelog.com/en/1.0.0/

**Comment by whispersofthedawn** [comment]
Can I suggest that the CHANGELOG.md simply links to the book (or vice versa)? Maintaining two sounds like kind of a pain, whereas you could just link to the generated mdbook file (either the source file or the hosted version (GitHub pages?)).

**Comment by John15321** [comment]
> Can I suggest that the CHANGELOG.md simply links to the book (or vice versa)? Maintaining two sounds like kind of a pain, whereas you could just link to the generated mdbook file (either the source file or the hosted version (GitHub pages?)).

that's the point of this issue https://github.com/John15321/rust-pip/issues/34
